title: Gangadhar Gardas 1st GitHub Page create experience
author: Gangadhar Gardas
email: gardasgangadhar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the 1st GitHub page I am creating.
  And I am providing my experience here.
  Please keep refresh for more updates.
  Enjoy your day :-)

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
